### ISSUE TITLE
Start implementing the internationalization support for the application.

### ISSUE THREAD

**Issue by AlvaroIC** [Arquisoft/wiq_en2a#17]
Start implementing the internationalization support for the application (Spanish, English and French, presumably).

**Comment by carolbgmm** [comment]
Found documentation about [how to implement i18n](https://dev.to/franklin030601/construyendo-una-app-multi-lenguaje-con-react-44n2#5)

**Comment by carolbgmm** [comment]
I18n applied to the first view, the login and the register.
