### ISSUE TITLE
Enhance current documentation.

### ISSUE THREAD

**Issue by AlvaroIC** [Arquisoft/wiq_en2a#25]
Enhance current documentation and correct errors.

**Comment by carolbgmm** [comment]
Modify name: from 'Template' to 'Wiq_en2a' or something in that line.

1.2:
- Do we think the image is necessary? No? Remove : Let it be
- Prioritize quality goals. Is that important the security in a game?
1.3:
- Remove teacher's email and any other personal information that may be in the document.
1.4:
- Remove.
2.1:
- Any decision must also be reflected in the wiki if not already with the reasons.
3.1:
- Change diagram
- Question generation inside the system
3.2:
- Should be just a little more specific than 3.1. Now it's too specific. No need to show everything.
- MongoDB outside of the system.
- If we use a MongoDB service, it can be specified inside the system that it's a service.
4.2:
- Remove Arc42, Docker and Wikidata. Wikidata is a constraint, not a decision.
- In case that we find a WikidataAPI that we want to use, it can be there, but specifying that it's an API.
7.1:
- Not recommended to use the same diagram in two different sections for maintainability.
8.1:
- No titles in the arrows.
- Mixed things: WikidataApi with SPARQL, gateway, question generation...
- Add some text that explains the diagram.
10.1:
- Diagram not matching the following table.
- Question generation is not a quality attibute.
10.2:
- Lack of information.
11:
- We can already find some risks.
12:
- Specify definitions of any technical word that is not explained but used in the document.
