### ISSUE TITLE
Document the first sections of the Arc42 documentation.

### ISSUE THREAD

**Issue by AlvaroIC** [Arquisoft/wiq_en2a#5]
Document the first four sections of the Arc42 documentation (Introduction and Goals, Architecture Contraints, System Scope and Context and Solution Strategy).

**Comment by pelazas** [comment]
Section 2 of the documentation done

**Comment by UO287741** [comment]
Section 1 and 3 partially done (some individual points: 1.2 and 2.2  must be addressed later on production)

**Comment by carolbgmm** [comment]
Section 4 of the documentation done.

**Comment by UO287741** [comment]
Visualization errors solved
