### ISSUE TITLE
Design and create the first version of the views of the application.

### ISSUE THREAD

**Issue by AlvaroIC** [Arquisoft/wiq_en2a#6]
Design and create the first version of the views of the application using Figma.

**Comment by pelazas** [comment]
### Version 1 of the game screens
Available in this figma file: https://www.figma.com/file/WD9j3Oxi2zcXl7DxziDIk4/Main?type=design&node-id=20-343&mode=design&t=IdrTLj25iUhYO15g-0

![Game Screen 1(v1)](https://github.com/Arquisoft/wiq_en2a/assets/108868934/8d88a105-b85e-4b89-917c-f1cf8f9816ac)

![Game Screen 2 - Single player (v1)](https://github.com/Arquisoft/wiq_en2a/assets/108868934/72c91a99-3681-4529-bcbd-b421e3d00bf1)

![Game Screen 3 - Multiplayer (v1)](https://github.com/Arquisoft/wiq_en2a/assets/108868934/1c6bcc56-354f-437a-9bd0-db14d6a1f5c4)

![Game Screen 4 - Multiplayer - Create Party (v1)](https://github.com/Arquisoft/wiq_en2a/assets/108868934/638b84ba-f3b4-469e-b8ed-135b6a183394)

![Game Screen 5 - Multiplayer - Party Room (v1)](https://github.com/Arquisoft/wiq_en2a/assets/108868934/e59c5b38-db84-4a66-a504-9cd89e12cbb1)

![Game Screen 6 - Multiplayer - Join Party (v1)](https://github.com/Arquisoft/wiq_en2a/assets/108868934/5c593ec1-3e2b-4161-b7bf-bcdab31825c0)

![Game Screen 7 - Game (v1)](https://github.com/Arquisoft/wiq_en2a/assets/108868934/2f5a4f6b-d053-45ae-8c6c-aef5356c4564)

![Game Screen 8 - Multiplayer - Ranking (v1)](https://github.com/Arquisoft/wiq_en2a/assets/108868934/0b5a2f62-b16c-4fcd-85ae-7462c6f6cba1)

**Comment by pelazas** [comment]
### Version 1 of group screens

Available in this figma file: https://www.figma.com/file/WD9j3Oxi2zcXl7DxziDIk4/Views?type=design&node-id=74-314&mode=design&t=nDilwunzKeOwPQjW-0

![Groups Screen - No groups assigned](https://github.com/Arquisoft/wiq_en2a/assets/108868934/884de2de-5f9a-4a07-915b-9ddf254495af)

![Groups Screen - No groups assigned - Join Group](https://github.com/Arquisoft/wiq_en2a/assets/108868934/9c116c65-0bed-45a2-97da-bd48718face0)

![Groups Screen - No groups assigned - Create Group](https://github.com/Arquisoft/wiq_en2a/assets/108868934/14f09987-7135-4321-8de4-13ee6a79bf3e)

![Groups Screen - Group view](https://github.com/Arquisoft/wiq_en2a/assets/108868934/1d8a68d9-d9a9-4ae9-9991-7d3f64b1b81a)

![Groups Screen - Group view - Settings](https://github.com/Arquisoft/wiq_en2a/assets/108868934/ca9cf7de-5aaa-4906-b0ef-cc4d6e0ba2c8)

**Comment by AlvaroIC** [comment]
### Version 1 of the game screens

Available in this figma file: https://www.figma.com/file/WD9j3Oxi2zcXl7DxziDIk4/Main?type=design&node-id=20-343&mode=design&t=IdrTLj25iUhYO15g-0
![Log in screen (v1)](https://github.com/Arquisoft/wiq_en2a/assets/98840489/9ef164c0-c096-40b3-af57-57e4fe9292fb)
![Game Screen 1 - Playing style (v2)](https://github.com/Arquisoft/wiq_en2a/assets/98840489/8193c58e-a6aa-4194-839c-25c8acd44aff)
![Game Screen 2 - Game option (v2)](https://github.com/Arquisoft/wiq_en2a/assets/98840489/58c73654-a9b3-47a0-9683-4f74b4ad1a1d)
![Game Screen 3 - Game mode (v2)](https://github.com/Arquisoft/wiq_en2a/assets/98840489/766168e6-53d2-4e0e-81a4-c94c1fc14b5c)
![Game Screen 4 - Create room (v2)](https://github.com/Arquisoft/wiq_en2a/assets/98840489/1b01df8c-17bb-4927-8d2a-b09187c72acb)
![Game Screen 5 - Join room code (v2)](https://github.com/Arquisoft/wiq_en2a/assets/98840489/3adaccfc-3b2e-4121-b540-d24a846ff30c)
![Game Screen 6 - Search for a public room (v2)](https://github.com/Arquisoft/wiq_en2a/assets/98840489/14b178cd-aac2-4d1b-9711-b6482288f1bf)
![Game Screen 7 - Lobby (v2)](https://github.com/Arquisoft/wiq_en2a/assets/98840489/bb5a1d36-f28e-4040-bfd0-426a8eaeaddd)
![Game Screen 8 - Questions (v2)](https://github.com/Arquisoft/wiq_en2a/assets/98840489/d01de1fc-f6f5-4a9e-9a1d-f0661215096b)
![Groups Screen - Create Group (v1)](https://github.com/Arquisoft/wiq_en2a/assets/98840489/dfaaf347-9693-4311-b79a-cc5924e093ca)
![Groups Screen - Group view - Settings](https://github.com/Arquisoft/wiq_en2a/assets/98840489/922d1f3e-6a7a-48ca-9330-d7d40b3d6cbe)
![Groups Screen - Group view (v1)](https://github.com/Arquisoft/wiq_en2a/assets/98840489/84f4abdf-f25b-46d4-b02c-33a908321e2b)
![Groups Screen - Join group (v1)](https://github.com/Arquisoft/wiq_en2a/assets/98840489/3876ef6d-59e2-49d0-8f54-f2e5b48a8298)
![Groups Screen 1 - No groups assigned (v1)](https://github.com/Arquisoft/wiq_en2a/assets/98840489/45153ab0-f6d4-4d4e-8f42-0b28c3790cd5)
![Scoreboard Screen 1 - Individual scoreboard (v1)](https://github.com/Arquisoft/wiq_en2a/assets/98840489/fd852812-e1a3-4dc1-bba4-894b38caed34)
![Scoreboard Screen 2 - Group scoreboard (v1)](https://github.com/Arquisoft/wiq_en2a/assets/98840489/0e54611b-8c03-4b52-9a83-5abe72f14338)

**Comment by AlvaroIC** [comment]
Now that the all the main views have been created, we will keep updating them.
