### ISSUE TITLE
Error when trying to deploy from local repository

### ISSUE THREAD

**Issue by UO287741** [Arquisoft/wiq_en2a#8]
I have started working on the documentation Issue and wanted to deploy it, i used npm run deploy but this is the output i get:

ENOENT: no such file or directory, stat 'C:\Users\Equipo\Desktop\ASW-Project\wiq_en2a\docs\build'

It is already built locally, i must be missing something. Im also executing the command from the docs folder

**Comment by pelazas** [comment]
Issue solved in call
